### ISSUE TITLE
Jodd + Java 8 : getting error INVOKESPECIAL/STATIC on interfaces require ASM 5

### ISSUE THREAD

**Issue by ppoulard** [oblac/jodd#196]
Hi,

I invoke Methref like shown in the doc, usually, it works. 
But it doesn't work on a class that use some code on an interface with a default method (Java 8). Jodd doesn't seem to support it :
```
Caused by: java.lang.IllegalArgumentException: INVOKESPECIAL/STATIC on interfaces require ASM 5
	at jodd.asm5.MethodVisitor.visitMethodInsn(MethodVisitor.java:477)
	at jodd.asm5.ClassReader.readCode(ClassReader.java:1416)
	at jodd.asm5.ClassReader.readMethod(ClassReader.java:1017)
	at jodd.asm5.ClassReader.accept(ClassReader.java:693)
	at jodd.asm5.ClassReader.accept(ClassReader.java:506)
	at jodd.proxetta.ProxettaBuilder.process(ProxettaBuilder.java:181)
	at jodd.proxetta.ProxettaBuilder.define(ProxettaBuilder.java:224)
	at jodd.methref.MethrefProxetta.defineProxy(MethrefProxetta.java:33)
	at jodd.methref.Methref.<init>(Methref.java:34)
	at jodd.methref.Methref.on(Methref.java:53)
```
The message seems complain about a missing requirement (ASM 5), but the name of the package suggest it is already the case (jodd.asm5...)

What am I supposed to do ?

Regards,
Philippe

**Comment by igorspasic** [comment]
I will check it out:) It looks it is related to ASM library... Others have similar problems (and [solutions](https://github.com/Sable/soot/commit/1e2225b2797c1877eedd68114db3d4086e16b524))

**Comment by igorspasic** [comment]
I have update to ASM5 usage; now the default methods get wrapped as any other methods.

Would you be so kind to check master if it works for you? Thank you!

And thank you very much for submitting issue! Hope the fix will work for you :)

**Comment by ppoulard** [comment]
So far, I have refactored my code, and the part that were using Java 8 features is no longer reachable during the scan : it works...
Tx for your help

**Comment by igorspasic** [comment]
No problem!
