### ISSUE TITLE
bugs about proxetta

### ISSUE THREAD

**Issue by kvchoi** [oblac/jodd#215]
Now i try proxetta  in maven project or playframework to find how to integrate in my project.
but it doesn't pass a simple junit test.
=====
my code:
```
        ProxyAspect aspect = new ProxyAspect(ScopedProxyAdvice.class, new AllMethodsPointcut());
        ProxyProxetta proxetta = new ProxyProxetta(aspect);
        ProxyProxettaBuilder builder = proxetta.builder();
        builder.setTarget(TestDao.class);
        Class<TestDao> proxyDao = builder.define();
        System.out.println(proxyDao.getName());
        TestDao dao = (TestDao) builder.newInstance();
        dao.store(12);
```
=================

the problem cause in line `TestDao dao = (TestDao) builder.newInstance();` with exception:

```
java.lang.ArrayIndexOutOfBoundsException: 6
	at jodd.asm5.ClassReader.readShort(ClassReader.java:2326)
	at jodd.asm5.ClassReader.<init>(ClassReader.java:169)
	at jodd.asm5.ClassReader.<init>(ClassReader.java:153)
	at jodd.asm5.ClassReader.<init>(ClassReader.java:424)
	at jodd.proxetta.ProxettaBuilder.process(ProxettaBuilder.java:174)
	at jodd.proxetta.ProxettaBuilder.define(ProxettaBuilder.java:224)
	at jodd.proxetta.ProxettaBuilder.newInstance(ProxettaBuilder.java:275)
	at base.DaoEnhancer.enhance(DaoEnhancer.java:19)
	at services.TestService.enhanceAdd(TestService.java:50)
	at ApplicationTest.testDao(ApplicationTest.java:21)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at jws.test.JwsJUnitRunner$StartJws$1$1$1.execute(JwsJUnitRunner.java:74)
	at jws.Invoker$Invocation.run(Invoker.java:275)
	at jws.Invoker.invokeInThread(Invoker.java:75)
	at jws.test.JwsJUnitRunner$StartJws$1$1.evaluate(JwsJUnitRunner.java:69)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at jws.test.JwsJUnitRunner.run(JwsJUnitRunner.java:49)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
```

so i follow into the code find that `is.available()` method always return `0`:

```
 private static byte[] readClass(final InputStream is, boolean close)
            throws IOException {
        if (is == null) {
            throw new IOException("Class not found");
        }
        try {
            byte[] b = new byte[is.available()];
```

what should i do to avoid this ?

**Comment by kvchoi** [comment]
in addition:
System.out.println(proxyDao.getName()); 
can print value:
daos.TestDao$$Proxetta

**Comment by igorspasic** [comment]
This looks like ASM issue - library we are using for bytecode stuff. Would you be so kind to show me your `TestDao` class? Which version of Java?

Thank you!

**Comment by igorspasic** [comment]
Please forgive me for not responding on this issue quickly as usually - I will fix this in this week. Btw, if you can send these sources or snippets, that might speed up the process :)

**Comment by kvchoi** [comment]
maybe i try the test in a wrong way,  after i class i used in the testunit is contains static method.
