### ISSUE TITLE
SSL peer shut down incorrectly

### ISSUE THREAD

**Issue by liniu** [oblac/jodd#253]
Remote host closed connection during handshake; <--- java.io.EOFException: SSL peer shut down incorrectly
        at jodd.http.net.SocketHttpConnectionProvider.createHttpConnection(SocketHttpConnectionProvider.java:88) ~[jodd3.6.7.jar:?]
        at jodd.http.HttpRequest.open(HttpRequest.java:621) ~[jodd3.6.7.jar:?]
        at jodd.http.HttpRequest.open(HttpRequest.java:608) ~[jodd3.6.7.jar:?]
        at jodd.http.HttpRequest.send(HttpRequest.java:699) ~[jodd3.6.7.jar:?]

**Comment by igorspasic** [comment]
Hello!

If this is what I think it is, then it is most easily controlled by the `https.protocols` system property. This is how you are able to control what the factory method returns. Set to "TLSv1" for example. Experiment with:

    -Dhttps.protocols=TLSv1,SSLv3

Does this helps?

**Comment by liniu** [comment]
@igorspasic  Thank you very much ,I will try it ，Can be caused by network congestion?

**Comment by igorspasic** [comment]
Any news on this, @liniu ?

**Comment by liniu** [comment]
never happened again

**Comment by igorspasic** [comment]
Nice :)
