### ISSUE TITLE
NumberFormatException in HttpClient

### ISSUE THREAD

**Issue by pawelantczak** [oblac/jodd#299]
Hello.
I'm getting something like this:
```
java.lang.NumberFormatException: For input string: "HTML"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65) ~[na:1.8.0_72]
	at java.lang.Integer.parseInt(Integer.java:580) ~[na:1.8.0_72]
	at java.lang.Integer.parseInt(Integer.java:615) ~[na:1.8.0_72]
	at jodd.http.HttpResponse.readFrom(HttpResponse.java:222) ~[jodd-http-3.6.7.jar!/:3.6.7]
	at jodd.http.HttpRequest.send(HttpRequest.java:711) ~[jodd-http-3.6.7.jar!/:3.6.7]
	at jodd.http.HttpBrowser.sendRequest(HttpBrowser.java:148) ~[jodd-http-3.6.7.jar!/:3.6.7]
```
I will try to track exact url which can reproduce this error.
Regards.

**Comment by igorspasic** [comment]
It looks like status code number is missing from response?

    Status-Line = HTTP-Version SP Status-Code SP Reason-Phrase CRLF

Can you send request using e.g. `curl` or `httpie` and check the response header?

**Comment by igorspasic** [comment]
Heya, any news with this? Is there something I can help?
