### ISSUE TITLE
java.lang.NoSuchMethodError: jodd.io.StreamUtil.close(Ljava/io/Closeable;)V

### ISSUE THREAD

**Issue by ShrCheng** [oblac/jodd#303]
java.lang.NoSuchMethodError: jodd.io.StreamUtil.close(Ljava/io/Closeable;)V
	at jodd.madvoc.result.TextResult.render(TextResult.java:63)
	at jodd.madvoc.result.TextResult.render(TextResult.java:40)
	at jodd.madvoc.component.MadvocController.render(MadvocController.java:230)
	at jodd.madvoc.ActionRequest$1.invoke(ActionRequest.java:224)
	at jodd.madvoc.ActionRequest.invoke(ActionRequest.java:345)
	at jodd.madvoc.component.MadvocController.invoke(MadvocController.java:164)
	at jodd.madvoc.MadvocServletFilter.doFilter(MadvocServletFilter.java:111)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:142)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:617)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:518)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1091)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:668)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1527)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1484)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)

this is source code

`import jodd.madvoc.meta.Action;
import jodd.madvoc.meta.MadvocAction;
import jodd.madvoc.meta.Out;

@MadvocAction()
public class TimelineAction {
    
    @Out
    String json;
    
    @Action("/timeline/timelines.json")
    public String footers() {
        return "text:你好";
    }
    
}
`

**Comment by igorspasic** [comment]
Hey! Are you sure you have updated all Jodd jars in your project (here its `jodd-core.jar`)?

`jodd.io.StreamUtil.close(java/io/Closeable)` was added not so long ago. So just please check the versions.

**Comment by ShrCheng** [comment]
<dependency>
            <groupId>org.jodd</groupId>
            <artifactId>jodd-madvoc</artifactId>
            <version>3.7</version>
        </dependency>
        <dependency>
            <groupId>org.jodd</groupId>
            <artifactId>jodd-http</artifactId>
            <version>3.7</version>
        </dependency>
        <dependency>
            <groupId>org.jodd</groupId>
            <artifactId>jodd-core</artifactId>
            <version>3.6.7</version>
        </dependency>


this is my jodd dependencys

**Comment by igorspasic** [comment]
Hm, strange - are you sure you dont have old `jodd-core` in your classpath (required by some other dependency :)))?

Can you please also check this example here: https://github.com/oblac/jodd-quickstart/tree/master/madvoc

I have just upgraded to version 3.7 and it worked here.

**Comment by ShrCheng** [comment]
Thank you, have been solved!
I update the jodd p-code version to 3.7
No immediate effect, buffer problem
Thank you very mush
