### ISSUE TITLE
Fails to connect to HTTPS endpoint

### ISSUE THREAD

**Issue by igorspasic** [oblac/jodd#356]
Jodd-http fails to read:

    https://restcountries.eu/rest/v1/all

while it works without https. Also, this works fine:

    curl -XGET https://restcountries.eu/rest/v1/all

Cause exception:

```
---[cause]------------------------------------------------------------------------
sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:141)
	at sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:126)
	at java.security.cert.CertPathBuilder.build(CertPathBuilder.java:280)
	at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:382)
	at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:292)
	at sun.security.validator.Validator.validate(Validator.java:260)
	at sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:324)
	at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:229)
	at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:124)
	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1491)
	at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:216)
	at sun.security.ssl.Handshaker.processLoop(Handshaker.java:979)
	at sun.security.ssl.Handshaker.process_record(Handshaker.java:914)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1062)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1375)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1403)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1387)
	at jodd.http.net.SocketHttpConnectionProvider.createHttpConnection(SocketHttpConnectionProvider.java:43)
	at jodd.http.HttpRequest.open(HttpRequest.java:550)
	at jodd.http.HttpRequest.open(HttpRequest.java:537)
	at jodd.http.HttpRequest.send(HttpRequest.java:628)
```

**Comment by igorspasic** [comment]
openssl s_client -connect restcountries.eu:443/rest/v1/all -showcerts

```
CONNECTED(00000003)
depth=1 /C=IL/O=StartCom Ltd./OU=StartCom Certification Authority/CN=StartCom Class 1 DV Server CA
verify error:num=20:unable to get local issuer certificate
verify return:0
---
Certificate chain
 0 s:/CN=www.restcountries.eu
   i:/C=IL/O=StartCom Ltd./OU=StartCom Certification Authority/CN=StartCom Class 1 DV Server CA
-----BEGIN CERTIFICATE-----
MIIE9jCCA96gAwIBAgIQP3e9A8SQ6XgItXB4N1GyijANBgkqhkiG9w0BAQsFADB4
MQswCQYDVQQGEwJJTDEWMBQGA1UEChMNU3RhcnRDb20gTHRkLjEpMCcGA1UECxMg
U3RhcnRDb20gQ2VydGlmaWNhdGlvbiBBdXRob3JpdHkxJjAkBgNVBAMTHVN0YXJ0
Q29tIENsYXNzIDEgRFYgU2VydmVyIENBMB4XDTE2MDMwNTE0MTg1M1oXDTE3MDMw
NTE0MTg1M1owHzEdMBsGA1UEAwwUd3d3LnJlc3Rjb3VudHJpZXMuZXUwggEiMA0G
CSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDIMCkejq/PiUHmWgk+9DkTzVo2er2H
zMucIy5NOoAAuZhxeVhOBJNTwII+lZT+sR7y2lBXf2n5e9C2i9g/n2svbwTLZhIw
nUIhM+UgysIC3E3byQARpPF6r/j+3GygOWTzvxT2SmpyQX3i9eCKmEgiCrLyTmxQ
gGRIssGchIkJUXAiqls+6lShzeHM/ndk8HOkhK6KhRoBrl62xTGR00gIZOjrcJMr
shR92A+lKd1ZzhC4HsLugrQKVOOSqalXPkTGVCefmBgunaBCsojqRsn6zofwqSwn
5nVV+2fmEKzVcA+eay95mmol9D8mDII511AmAsuE/EuUC7ur+3SU+4I5AgMBAAGj
ggHTMIIBzzAOBgNVHQ8BAf8EBAMCBaAwHQYDVR0lBBYwFAYIKwYBBQUHAwIGCCsG
AQUFBwMBMAkGA1UdEwQCMAAwHQYDVR0OBBYEFC22/8nF5PjlBn0eQLcKvqmj/Qg6
MB8GA1UdIwQYMBaAFNeRTgHEsL/4yGeTRJznM/qtkwyvMG8GCCsGAQUFBwEBBGMw
YTAkBggrBgEFBQcwAYYYaHR0cDovL29jc3Auc3RhcnRzc2wuY29tMDkGCCsGAQUF
BzAChi1odHRwOi8vYWlhLnN0YXJ0c3NsLmNvbS9jZXJ0cy9zY2Euc2VydmVyMS5j
cnQwOAYDVR0fBDEwLzAtoCugKYYnaHR0cDovL2NybC5zdGFydHNzbC5jb20vc2Nh
LXNlcnZlcjEuY3JsMDEGA1UdEQQqMCiCFHd3dy5yZXN0Y291bnRyaWVzLmV1ghBy
ZXN0Y291bnRyaWVzLmV1MCMGA1UdEgQcMBqGGGh0dHA6Ly93d3cuc3RhcnRzc2wu
Y29tLzBQBgNVHSAESTBHMAgGBmeBDAECATA7BgsrBgEEAYG1NwECBDAsMCoGCCsG
AQUFBwIBFh5odHRwOi8vd3d3LnN0YXJ0c3NsLmNvbS9wb2xpY3kwDQYJKoZIhvcN
AQELBQADggEBAHywGqq/Ps62NKI4ci1I7wisGJ9K9pht/vhWfujtOpQUtQ9chzAb
iXI9VzmZgZRUwgleOlqd21vQGOIKhFOh8pA1izoZ2d4SW7+9YtPmpINqijG8NhHt
9TQodUdVK3B+R6rBU9CqxBNxMww/5tPw3nF61mxXkpmjBztp0OS6fMvZvu/bj8FV
A6LlliT+c9MGCyTDMmy5i30o0f7rOJqTehAYG+8Qc2fFm6JQ+KM5CJaOjaJ1XEPy
4tBfe4NwP4o+Ni+ldpRJdO5v9atmpjk3zzucF7+pI8FkhQChJNCpY21nLPmuPYH+
fPC3HqWCBVwgetN7TxZM2Kqu4wsZLtqwohY=
-----END CERTIFICATE-----
 1 s:/C=IL/O=StartCom Ltd./OU=StartCom Certification Authority/CN=StartCom Class 1 DV Server CA
   i:/C=IL/O=StartCom Ltd./OU=Secure Digital Certificate Signing/CN=StartCom Certification Authority
-----BEGIN CERTIFICATE-----
MIIF5TCCA82gAwIBAgIQal3D5TtOT9B7aR6l/OxkazANBgkqhkiG9w0BAQsFADB9
MQswCQYDVQQGEwJJTDEWMBQGA1UEChMNU3RhcnRDb20gTHRkLjErMCkGA1UECxMi
U2VjdXJlIERpZ2l0YWwgQ2VydGlmaWNhdGUgU2lnbmluZzEpMCcGA1UEAxMgU3Rh
cnRDb20gQ2VydGlmaWNhdGlvbiBBdXRob3JpdHkwHhcNMTUxMjE2MDEwMDA1WhcN
MzAxMjE2MDEwMDA1WjB4MQswCQYDVQQGEwJJTDEWMBQGA1UEChMNU3RhcnRDb20g
THRkLjEpMCcGA1UECxMgU3RhcnRDb20gQ2VydGlmaWNhdGlvbiBBdXRob3JpdHkx
JjAkBgNVBAMTHVN0YXJ0Q29tIENsYXNzIDEgRFYgU2VydmVyIENBMIIBIjANBgkq
hkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA2uz0qohni7BLYmaWv8lEaObCK0ygM86s
eeN2w9FW4HWvQbQKRYDvy43kFuMmFD4RHkHn1Mk7sijXkJ/F8NH+5Tjbins7tFIC
ZXd+Qe2ODCMcWbOLoYB54sM514tsZk6m3M4lZi3gmT7ISFiNdKpf/C3dZwasWea+
dbLpwQWZEcM6oCXmW/6L3kwQAhC0GhJm2rBVrYEDvZq1EK3Bv+g5gAW8DVfusUai
oyW0wfQdnKtOLv1M4rtezrKtE8T5tjyeKvFqMX93+LYVlT8Vs+sD12s3ncldqEDL
U89IiBjg6FsbLfM2Ket/3RbfvggfQMPQshipdhrZL8q10jibTlViGQIDAQABo4IB
ZDCCAWAwDgYDVR0PAQH/BAQDAgEGMB0GA1UdJQQWMBQGCCsGAQUFBwMCBggrBgEF
BQcDATASBgNVHRMBAf8ECDAGAQH/AgEAMDIGA1UdHwQrMCkwJ6AloCOGIWh0dHA6
Ly9jcmwuc3RhcnRzc2wuY29tL3Nmc2NhLmNybDBmBggrBgEFBQcBAQRaMFgwJAYI
KwYBBQUHMAGGGGh0dHA6Ly9vY3NwLnN0YXJ0c3NsLmNvbTAwBggrBgEFBQcwAoYk
aHR0cDovL2FpYS5zdGFydHNzbC5jb20vY2VydHMvY2EuY3J0MB0GA1UdDgQWBBTX
kU4BxLC/+Mhnk0Sc5zP6rZMMrzAfBgNVHSMEGDAWgBROC+8apEBbpRdphzDKNGhD
0EGu8jA/BgNVHSAEODA2MDQGBFUdIAAwLDAqBggrBgEFBQcCARYeaHR0cDovL3d3
dy5zdGFydHNzbC5jb20vcG9saWN5MA0GCSqGSIb3DQEBCwUAA4ICAQCO5z+95Eu6
gog9K9e7DatQXfeUL8zq1Ycj0HKo3ZvFhRjULAVrMj7JrURtfoZziTDl39gvMDhL
voN5EFEYQWyre5ySsFgGeZQHIC0zhETILSyAE7JCKaEJ//APnkcQfx458GOuJvi+
p2JpRxa8Sc/HVJ9HqA687QbbJFFZlUP5IqLtCb8yZVBURd4Nm/+01DXBzomoQPwA
K3cYl9br6Q+eKmCKPKN6X4IT1gwtwXuca1f3OpZTbUFPdPz1KvP1qCFt+rNieSmO
BN76Xa9ffzoBByzVdnvk2OHuopmJq/eHF+E3s+GFYT6Oxjrez/lEbBvgEmGyXZOZ
aj6XeDnBxOIYRODfnZG99cy2q5WtDLHKuiMogJGO89PWaI2jK1Aq5sa0j55jp2Je
FXbRieKw5CKreCIiNR9MpaffieLgbTcK1BSKjxUZtd7BqJ3x1lvD2jbe7WKqzusZ
btPhFgrDDsgdw27zQokNYBZZaa1LwYZGZgddiAcLcYkilGobA2wLKk6eYz6VnatD
dI4aQx6FkHWvKU0e7s/cUym6Px3vXrC4z6woAztC98XaorPO0pkL73P4dKSjnKYY
rYsqe7BnBGtANf1XaG5Pm8BUWJ9WZAWin6KsJXTo8Nj0G4CRq7dq17LBnCbi9Qmp
Szc2kuPNbrV8PvbTLIXupfZFFj0d9mpaFg==
-----END CERTIFICATE-----
---
Server certificate
subject=/CN=www.restcountries.eu
issuer=/C=IL/O=StartCom Ltd./OU=StartCom Certification Authority/CN=StartCom Class 1 DV Server CA
---
No client certificate CA names sent
---
SSL handshake has read 3745 bytes and written 456 bytes
---
New, TLSv1/SSLv3, Cipher is DHE-RSA-AES256-SHA
Server public key is 2048 bit
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
SSL-Session:
    Protocol  : TLSv1
    Cipher    : DHE-RSA-AES256-SHA
    Session-ID: 1B9E1E654CCF0F49A1B3C323E4E73D901C5DD91129117CB4F27AC992FC2CE93A
    Session-ID-ctx:
    Master-Key: 2A7E16E86507B608CC62573872612D78B8D962772FBF0E174B090E2DD0F0FF68231EC05CFD69A02C0D43CF090FF2657D
    Key-Arg   : None
    Start Time: 1478775561
    Timeout   : 300 (sec)
    Verify return code: 0 (ok)
---
```

**Comment by Laky753** [comment]
It's general java problem, you have to import the public certificate into yours jvm keystore or initialize your SSLContext with TrustManger trusting your certificate (possibly all certificates)

**Comment by igorspasic** [comment]
Hey @Laky753 thank you! I am just about to add this option(s) - way to trust all certificates (or just for target host) and to make easy import into the keystore... Thanx!

**Comment by igorspasic** [comment]
See this gist for bash script that imports the startssl certificates:

https://gist.github.com/igorspasic/e0c8ded2d5b624dd9a2b514c451133d4#file-install-startssl-certs-sh
