### ISSUE TITLE
jodd.db.oom.sqlgen.DbSqlBuilderException: Duplicated table reference:

### ISSUE THREAD

**Issue by titanseason** [oblac/jodd#378]
I'm using `DbOomQuery `like this:
```
public int unstar(long feedId, String uid) {
    DbSqlBuilder builder = DbSqlBuilder.sql().append("delete from ").table(Star.class, null).append(" where ").append("(").ref(null, "feedId").append(" = ").columnValue(feedId).append(AND).ref(null, "uid").append(" = ").columnValue(uid).append(")");
    log.debug(builder.generateQuery()); // delete from STAR where (FEED_ID = :p0 and UID = :p1)
    DbOomQuery.query(builder).autoClose().executeUpdate();
}
```
But an exception happened:
```
delete from STAR where (FEED_ID = :p0 and UID = :p1)
jodd.db.oom.sqlgen.DbSqlBuilderException: Duplicated table reference: Star
	at jodd.db.oom.sqlgen.TemplateData.registerTableReference(TemplateData.java:188)
	at jodd.db.oom.sqlgen.chunks.TableChunk.init(TableChunk.java:129)
	at jodd.db.oom.sqlgen.DbSqlBuilder.generateQuery(DbSqlBuilder.java:196)
	at jodd.db.oom.DbOomQuery.<init>(DbOomQuery.java:112)
	at jodd.db.oom.DbOomQuery.query(DbOomQuery.java:116)
	at com.uudove.api.dao.StarDao.unstar(StarDao.java:46)
	at com.uudove.api.dao.StarDao$$Proxetta.unstar$0(Unknown Source)
	at com.uudove.api.dao.StarDao$$Proxetta.unstar(Unknown Source)
	at com.uudove.api.service.FeedService.unstar(FeedService.java:101)
	at com.uudove.api.service.FeedService$$Proxetta.unstar$0(Unknown Source)
	at com.uudove.api.service.FeedService$$Proxetta.unstar(Unknown Source)
	at com.uudove.api.action.FeedAction.unstar(FeedAction.java:70)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at jodd.madvoc.ActionRequest.invokeActionMethod(ActionRequest.java:355)
	at jodd.madvoc.ActionRequest$2.invoke(ActionRequest.java:241)
	at jodd.madvoc.ActionRequest.invoke(ActionRequest.java:345)
	at com.uudove.api.interceptor.AuthInterceptor.intercept(AuthInterceptor.java:43)
	at jodd.madvoc.interceptor.BaseActionInterceptor.invoke(BaseActionInterceptor.java:38)
	at jodd.madvoc.ActionRequest.invoke(ActionRequest.java:345)
	at jodd.madvoc.interceptor.ServletConfigInterceptor.intercept(ServletConfigInterceptor.java:71)
	at jodd.madvoc.interceptor.BaseActionInterceptor.invoke(BaseActionInterceptor.java:38)
	at jodd.madvoc.ActionRequest.invoke(ActionRequest.java:345)
	at jodd.joy.i18n.I18nInterceptor.intercept(I18nInterceptor.java:45)
	at jodd.madvoc.interceptor.BaseActionInterceptor.invoke(BaseActionInterceptor.java:38)
	at jodd.madvoc.ActionRequest.invoke(ActionRequest.java:345)
	at jodd.madvoc.interceptor.EchoInterceptor.intercept(EchoInterceptor.java:66)
	at jodd.madvoc.interceptor.BaseActionInterceptor.invoke(BaseActionInterceptor.java:38)
	at jodd.madvoc.ActionRequest.invoke(ActionRequest.java:345)
	at jodd.madvoc.ActionRequest$1.invoke(ActionRequest.java:222)
	at jodd.madvoc.ActionRequest.invoke(ActionRequest.java:345)
	at jodd.madvoc.component.MadvocController.invoke(MadvocController.java:164)
	at jodd.madvoc.MadvocServletFilter.doFilter(MadvocServletFilter.java:111)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:233)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:191)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:127)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:109)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:293)
	at org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:859)
	at org.apache.coyote.http11.Http11Protocol$Http11ConnectionHandler.process(Http11Protocol.java:610)
	at org.apache.tomcat.util.net.JIoEndpoint$Worker.run(JIoEndpoint.java:503)
	at java.lang.Thread.run(Unknown Source)
```

**Comment by titanseason** [comment]
When I am using `DbSqlBuilder.columnValue`, sometimes it generates `key=?`, but sometimes it generates `key=:p0`, why?

**Comment by igorspasic** [comment]
Hey @titanseason! Let me try to answer this before trying it out locally:

This exception (`Duplicated table reference`) means that you have two classes that maps to the same table name (table reference). Do you have maybe something like that? Usually this happens when user have a class with different name (e.g. `StartView`), but uses the annotation to map it to the same table reference name (e.g. `@DbTable("star")`). Does you class has annotation?

You see `key=:p0` when **DbOom** manages the statement, since `key=?` is the default Java behavior. I am not sure why do you get the default behavior... usually, **DbOoom** manages all the statements:) If you see it, please let me know how did you get it, I might be more helpful.

One question: why don't you use [Template-SQL](http://jodd.org/doc/db/template-sql.html) instead of `DbSqlBuilder` manually? It is simply a bit easier to write, because you write everything in the string, for example:

    "delete from $T(star) where ($feedId = :p0 and $uid = :p1)"

**Comment by titanseason** [comment]
1. About `Duplicated table reference`:
    I have less than 5 tables in my project, and none is annotated by `@DbTable("STAR")`. By the way, I wrote a demo project [here ](https://pan.baidu.com/s/1jHCjkHK)(the core class is UserDao), after tomcat started, just input http://localhost:8080/passport/oauth/login in any browser, this exception will happen.
	
2. About `key=?`
    First, let `UserDao extends GenericDao`
	Then, `User user = this.findOneByProperty(User.class, "username", username);`
	And, the console has output `[jodd.db.DbQueryBase] [DEBUG] - Executing statement: select User_._id, ..., User_.USERNAME from USER User_ where User_.USERNAME=?`
	
3. About `Template-SQL`
    I am new to jodd, and I will try to use `Template-SQL`

**Comment by titanseason** [comment]
I'm trying to use `Template-SQL`, I find a new exception
```
DbSqlBuilder builder = DbSqlBuilder.sql("select * from $T{Star S} where $S.feedId = :p0"); // mark as 1
// DbSqlBuilder builder = DbSqlBuilder.sql("select * from $T{Star} where $feedId = :p0"); // mark as 2
// DbSqlBuilder builder = DbSqlBuilder.sql("delete from $T{Star} where $feedId = :p0"); // mark as 3
// DbSqlBuilder builder = DbSqlBuilder.sql("delete from $T{Star S} where $S.feedId = :p0"); //mark as 4
DbOomQuery query = DbOomQuery.query(builder);
query.setLong("p0", feedId);
```
Only the No.1 is running normally.

For No. 2
```
jodd.db.oom.sqlgen.DbSqlBuilderException: Invalid table reference: feedId Generated query: select * from STAR where 
	at jodd.db.oom.sqlgen.chunks.SqlChunk.lookupTableRef(SqlChunk.java:189)
	at jodd.db.oom.sqlgen.chunks.SqlChunk.lookupTableRef(SqlChunk.java:179)
	at jodd.db.oom.sqlgen.chunks.ReferenceChunk.process(ReferenceChunk.java:90)
	at jodd.db.oom.sqlgen.DbSqlBuilder.generateQuery(DbSqlBuilder.java:205)
	at jodd.db.oom.DbOomQuery.<init>(DbOomQuery.java:112)
	at jodd.db.oom.DbOomQuery.query(DbOomQuery.java:116)
	at com.uudove.api.dao.StarDao.unstar(StarDao.java:39)
	at com.uudove.api.dao.StarDao$$Proxetta.unstar$0(Unknown Source)
	at com.uudove.api.dao.StarDao$$Proxetta.unstar(Unknown Source)
	at com.uudove.api.service.FeedService.unstar(FeedService.java:101)
	at com.uudove.api.service.FeedService$$Proxetta.unstar$0(Unknown Source)
	at com.uudove.api.service.FeedService$$Proxetta.unstar(Unknown Source)
	at com.uudove.api.action.FeedAction.unstar(FeedAction.java:70)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at jodd.madvoc.ActionRequest.invokeActionMethod(ActionRequest.java:355)
	at jodd.madvoc.ActionRequest$2.invoke(ActionRequest.java:241)
	at jodd.madvoc.ActionRequest.invoke(ActionRequest.java:345)
	at com.uudove.bible.api.interceptor.AuthInterceptor.intercept(AuthInterceptor.java:41)
	at jodd.madvoc.interceptor.BaseActionInterceptor.invoke(BaseActionInterceptor.java:38)
	at jodd.madvoc.ActionRequest.invoke(ActionRequest.java:345)
	at jodd.madvoc.interceptor.ServletConfigInterceptor.intercept(ServletConfigInterceptor.java:71)
	at jodd.madvoc.interceptor.BaseActionInterceptor.invoke(BaseActionInterceptor.java:38)
	at jodd.madvoc.ActionRequest.invoke(ActionRequest.java:345)
	at jodd.joy.i18n.I18nInterceptor.intercept(I18nInterceptor.java:45)
	at jodd.madvoc.interceptor.BaseActionInterceptor.invoke(BaseActionInterceptor.java:38)
	at jodd.madvoc.ActionRequest.invoke(ActionRequest.java:345)
	at jodd.madvoc.interceptor.EchoInterceptor.intercept(EchoInterceptor.java:66)
	at jodd.madvoc.interceptor.BaseActionInterceptor.invoke(BaseActionInterceptor.java:38)
	at jodd.madvoc.ActionRequest.invoke(ActionRequest.java:345)
	at jodd.madvoc.ActionRequest$1.invoke(ActionRequest.java:222)
	at jodd.madvoc.ActionRequest.invoke(ActionRequest.java:345)
	at jodd.madvoc.component.MadvocController.invoke(MadvocController.java:164)
	at jodd.madvoc.MadvocServletFilter.doFilter(MadvocServletFilter.java:111)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:233)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:191)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:127)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:109)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:293)
	at org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:859)
	at org.apache.coyote.http11.Http11Protocol$Http11ConnectionHandler.process(Http11Protocol.java:610)
	at org.apache.tomcat.util.net.JIoEndpoint$Worker.run(JIoEndpoint.java:503)
	at java.lang.Thread.run(Unknown Source)
```

For No. 3
```
jodd.db.oom.sqlgen.DbSqlBuilderException: Invalid table reference: feedId Generated query: delete from STAR where 
	at jodd.db.oom.sqlgen.chunks.SqlChunk.lookupTableRef(SqlChunk.java:189)
	at jodd.db.oom.sqlgen.chunks.SqlChunk.lookupTableRef(SqlChunk.java:179)
	at jodd.db.oom.sqlgen.chunks.ReferenceChunk.process(ReferenceChunk.java:90)
	at jodd.db.oom.sqlgen.DbSqlBuilder.generateQuery(DbSqlBuilder.java:205)
	at jodd.db.oom.DbOomQuery.<init>(DbOomQuery.java:112)
	at jodd.db.oom.DbOomQuery.query(DbOomQuery.java:116)
	at com.uudove.api.dao.StarDao.unstar(StarDao.java:39)
	at com.uudove.api.dao.StarDao$$Proxetta.unstar$0(Unknown Source)
	at com.uudove.api.dao.StarDao$$Proxetta.unstar(Unknown Source)
	at com.uudove.api.service.FeedService.unstar(FeedService.java:101)
	at com.uudove.api.service.FeedService$$Proxetta.unstar$0(Unknown Source)
	at com.uudove.api.service.FeedService$$Proxetta.unstar(Unknown Source)
	at com.uudove.api.action.FeedAction.unstar(FeedAction.java:70)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at jodd.madvoc.ActionRequest.invokeActionMethod(ActionRequest.java:355)
	at jodd.madvoc.ActionRequest$2.invoke(ActionRequest.java:241)
	at jodd.madvoc.ActionRequest.invoke(ActionRequest.java:345)
	at com.uudove.bible.api.interceptor.AuthInterceptor.intercept(AuthInterceptor.java:41)
	at jodd.madvoc.interceptor.BaseActionInterceptor.invoke(BaseActionInterceptor.java:38)
	at jodd.madvoc.ActionRequest.invoke(ActionRequest.java:345)
	at jodd.madvoc.interceptor.ServletConfigInterceptor.intercept(ServletConfigInterceptor.java:71)
	at jodd.madvoc.interceptor.BaseActionInterceptor.invoke(BaseActionInterceptor.java:38)
	at jodd.madvoc.ActionRequest.invoke(ActionRequest.java:345)
	at jodd.joy.i18n.I18nInterceptor.intercept(I18nInterceptor.java:45)
	at jodd.madvoc.interceptor.BaseActionInterceptor.invoke(BaseActionInterceptor.java:38)
	at jodd.madvoc.ActionRequest.invoke(ActionRequest.java:345)
	at jodd.madvoc.interceptor.EchoInterceptor.intercept(EchoInterceptor.java:66)
	at jodd.madvoc.interceptor.BaseActionInterceptor.invoke(BaseActionInterceptor.java:38)
	at jodd.madvoc.ActionRequest.invoke(ActionRequest.java:345)
	at jodd.madvoc.ActionRequest$1.invoke(ActionRequest.java:222)
	at jodd.madvoc.ActionRequest.invoke(ActionRequest.java:345)
	at jodd.madvoc.component.MadvocController.invoke(MadvocController.java:164)
	at jodd.madvoc.MadvocServletFilter.doFilter(MadvocServletFilter.java:111)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:233)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:191)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:127)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:109)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:293)
	at org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:859)
	at org.apache.coyote.http11.Http11Protocol$Http11ConnectionHandler.process(Http11Protocol.java:610)
	at org.apache.tomcat.util.net.JIoEndpoint$Worker.run(JIoEndpoint.java:503)
	at java.lang.Thread.run(Unknown Source)
```
For No. 4
```
com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'S where S.FEED_ID = 1' at line 1
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
	at com.mysql.jdbc.Util.getInstance(Util.java:386)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1053)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4074)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4006)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2468)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2629)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2719)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2155)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2450)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2371)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2355)
	at jodd.db.DbQueryBase.executeUpdate(DbQueryBase.java:697)
	at jodd.db.DbQueryBase.executeUpdate(DbQueryBase.java:670)
	at jodd.db.DbQuery.executeUpdate(DbQuery.java:72)
	at com.uudove.api.dao.StarDao.unstar(StarDao.java:45)
	at com.uudove.api.dao.StarDao$$Proxetta.unstar$0(Unknown Source)
	at com.uudove.api.dao.StarDao$$Proxetta.unstar(Unknown Source)
	at com.uudove.api.service.FeedService.unstar(FeedService.java:101)
	at com.uudove.api.service.FeedService$$Proxetta.unstar$0(Unknown Source)
	at com.uudove.api.service.FeedService$$Proxetta.unstar(Unknown Source)
	at com.uudove.api.action.FeedAction.unstar(FeedAction.java:70)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at jodd.madvoc.ActionRequest.invokeActionMethod(ActionRequest.java:355)
	at jodd.madvoc.ActionRequest$2.invoke(ActionRequest.java:241)
	at jodd.madvoc.ActionRequest.invoke(ActionRequest.java:345)
	at com.uudove.bible.api.interceptor.AuthInterceptor.intercept(AuthInterceptor.java:41)
	at jodd.madvoc.interceptor.BaseActionInterceptor.invoke(BaseActionInterceptor.java:38)
	at jodd.madvoc.ActionRequest.invoke(ActionRequest.java:345)
	at jodd.madvoc.interceptor.ServletConfigInterceptor.intercept(ServletConfigInterceptor.java:71)
	at jodd.madvoc.interceptor.BaseActionInterceptor.invoke(BaseActionInterceptor.java:38)
	at jodd.madvoc.ActionRequest.invoke(ActionRequest.java:345)
	at jodd.joy.i18n.I18nInterceptor.intercept(I18nInterceptor.java:45)
	at jodd.madvoc.interceptor.BaseActionInterceptor.invoke(BaseActionInterceptor.java:38)
	at jodd.madvoc.ActionRequest.invoke(ActionRequest.java:345)
	at jodd.madvoc.interceptor.EchoInterceptor.intercept(EchoInterceptor.java:66)
	at jodd.madvoc.interceptor.BaseActionInterceptor.invoke(BaseActionInterceptor.java:38)
	at jodd.madvoc.ActionRequest.invoke(ActionRequest.java:345)
	at jodd.madvoc.ActionRequest$1.invoke(ActionRequest.java:222)
	at jodd.madvoc.ActionRequest.invoke(ActionRequest.java:345)
	at jodd.madvoc.component.MadvocController.invoke(MadvocController.java:164)
	at jodd.madvoc.MadvocServletFilter.doFilter(MadvocServletFilter.java:111)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:233)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:191)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:127)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:109)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:293)
	at org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:859)
	at org.apache.coyote.http11.Http11Protocol$Http11ConnectionHandler.process(Http11Protocol.java:610)
	at org.apache.tomcat.util.net.JIoEndpoint$Worker.run(JIoEndpoint.java:503)
	at java.lang.Thread.run(Unknown Source)
```

**Comment by igorspasic** [comment]
Here is the first answer :)))

The exception `Duplicated table reference` happens because you called `builder.generateQuery()` _twice_: the first one is explicitly in the log method, and the second time is within `query` execution. If you debug the logging line 47:

    //log.debug(builder.generateQuery());

your method works. Then how to debug the query? `generateQuery` was not designed to be used by end user; so then just debug the `query`:

	DbOomQuery query = query(builder).autoClose();
	log.debug(query.getQueryString());
	return query.find(User.class);

Even better, enable _debug mode_:

	DbOomQuery query = query(builder).autoClose();
	query.setDebugMode();
	log.debug(query.getQueryString());
	return query.find(User.class);

You will see even the values for the parameters in debug mode :)

Now I will check other questions :)

**Comment by igorspasic** [comment]
Now Template SQLs

    // 1
    DbSqlBuilder.sql("select * from $T{Star S} where $S.feedId = :p0");

Fine.

    // 2
    DbSqlBuilder.sql("select * from $T{Star} where $feedId = :p0");

Error, because you can't have just `$feedId`, the syntax is: `$tableReference.columnReference`.

    // 3
    DbSqlBuilder.sql("delete from $T{Star} where $feedId = :p0");

The same syntax error as in 2.

    // 4
    DbSqlBuilder.sql("delete from $T{Star S} where $S.feedId = :p0");

The generated SQL is wrong: MySql does not support table aliases in `delete`, i.e.:

    delete from STAR S where...

is wrong SQL syntax (not related to Jodd), so just dont use the alias :)

**Comment by igorspasic** [comment]
I will update DbOom to make this things more developer friendly. Stay tuned!

**Comment by igorspasic** [comment]
Also - if you are fine, we might close this issue? Please let me know!

**Comment by titanseason** [comment]
@igorspasic Thanks very much, now it works normally. The right delete template is: 
`DbSqlBuilder builder = DbSqlBuildersql("delete from $T{Star} where $Star.feedId = :feedId");`

**Comment by titanseason** [comment]
And please close this issure!
Thank you very much!
