### ISSUE TITLE
some doc need change

### ISSUE THREAD

**Issue by restmad** [oblac/jodd#471]
https://jodd.org/email/

POP3

// common info
Printf.out("%0x", email.getFlags());

may need change to
Printf.str

but after that, it's also not working correctly.

java.lang.IllegalArgumentException: Invalid format: 'x' is not one of 'sp'

	at jodd.format.PrintfFormat.newIllegalArgumentException(PrintfFormat.java:763)
	at jodd.format.PrintfFormat.form(PrintfFormat.java:756)
	at jodd.format.Printf.str(Printf.java:99)

**Comment by igr** [comment]
Thanx! The problem is that flags are no longer the bytes.

Fixed: https://github.com/oblac/jodd-site/commit/7a68438c2a9c14a473b57f98b75568b8d577b373
