### ISSUE TITLE
Methref does not work with Java9

### ISSUE THREAD

**Issue by stadler** [oblac/jodd#513]
Hi

Wen trying to invoke the following, java 9.0.1 compiled, code:
```Methref.on(myClass);```

with Methref I get the following exception:
```
java.lang.IllegalArgumentException
	at jodd.asm5.ClassReader.<init>(ClassReader.java:185)
	at jodd.asm5.ClassReader.<init>(ClassReader.java:168)
	at jodd.asm5.ClassReader.<init>(ClassReader.java:439)
	at jodd.proxetta.ProxettaBuilder.process(ProxettaBuilder.java:205)
	at jodd.proxetta.ProxettaBuilder.define(ProxettaBuilder.java:255)
	at jodd.methref.MethrefProxetta.defineProxy(MethrefProxetta.java:56)
	at jodd.methref.Methref.<init>(Methref.java:57)
	at jodd.methref.Methref.on(Methref.java:79)
```

The problem seems to be that ASM5.2 does not support Java9.
Probably an update to ASM6 could resolve the problem.

**Comment by moh-sushi** [comment]
Hi,

> The problem seems to be that ASM5.2 does not support Java9.

As far as i have read some articles / other issues , asm 6+ only supports Java 9.

here the link to asm 6 release : http://forge.ow2.org/forum/forum.php?forum_id=2576

**Comment by igr** [comment]
Thanx! Upgrading to ASM6 is pending, hopefully very soon! Thanx for the link!

**Comment by neroux** [comment]
> asm 6+ only supports Java 9.

The release notes wouldnt indicate 9-only and the class files are still compiled for 1.5.

**Comment by igr** [comment]
See: https://github.com/oblac/jodd/pull/527, work in progress

**Comment by igr** [comment]
It is fixed in the pull request. Still, need to fix some other Java9 things.

**Comment by igr** [comment]
Closed by https://github.com/oblac/jodd/pull/527. However, the Java9 compatibility remains an open issue.
