### ISSUE TITLE
I get an error when trying to get a verification code using JODD-HTTP

### ISSUE THREAD

**Issue by esionchiu** [oblac/jodd#588]
Exception in thread "main" java.lang.StringIndexOutOfBoundsException: String index out of range: 10
	at java.lang.String.charAt(String.java:658)
	at jodd.http.HttpUtil.extractHeaderParameter(HttpUtil.java:222)
	at jodd.http.HttpUtil.extractContentTypeCharset(HttpUtil.java:187)
	at jodd.http.HttpBase._header(HttpBase.java:190)
	at jodd.http.HttpBase.header(HttpBase.java:157)
	at jodd.http.HttpBase.readHeaders(HttpBase.java:885)
	at jodd.http.HttpResponse.readFrom(HttpResponse.java:247)
	at jodd.http.HttpRequest._send(HttpRequest.java:860)
	at jodd.http.HttpRequest.send(HttpRequest.java:820)
	at jodd.http.HttpBrowser._sendRequest(HttpBrowser.java:229)
	at jodd.http.HttpBrowser.sendRequest(HttpBrowser.java:150)

## Steps to Reproduce the Problem

Hello, I try to get an error when I get the verification code for this address "http://880.23460.net:8080/"。
Thank you！

```
HttpRequest request = HttpRequest.get("http://880.23460.net:8080/?__CBK=++++++++13842263");
        browser.sendRequest(request);

        browser.sendRequest(HttpRequest.get(browser.getHttpRequest().hostUrl())
                .path("/yzm.php")
                .query("time", Math.random())
        );

        System.out.println(browser.getHttpResponse());

```

**Comment by neroux** [comment]
There seems to be a problem when parsing the character set out of the content type.

Which content type did you get? A quick test returned `text/html; charset=utf-8`, which works fine. You must have got something different in that case. The way I read the code it might be that you did not get a character set but only `text/html;`. In that case the first `indexOf` would return a value larger than -1 but the following increment would reach out of bounds.

**Comment by esionchiu** [comment]
@neroux 
Thank you,
I did not explicitly fill in the character code, nor did I fill in the accept value.
It was just an error when I was getting a verification code.

**Comment by neroux** [comment]
My assumption is the server sent an invalid content type. Maybe `extractHeaderParameter` could do with a bit of hardening in that case.

**Comment by igr** [comment]
Sorry, this was an issue in the code; your server returns header in form that we failed to parse.
