### ISSUE TITLE
ProxettaException while DbQuery.setInteger

### ISSUE THREAD

**Issue by titanseason** [oblac/jodd#609]
Jodd version is 4.3.2

I'm using quartz and new a dao with
 `ConvertTaskDao dao =petiteContainer.getBean(ConvertTaskDao.class);`, 

and have a sql builder like:
```
String sql = "select * from $T{ConvertTask t} where $t.state = :stateIdle limit 5";
DbOomQuery query = DbOomQuery.query(DbSqlBuilder.sql(sql));
query.setInteger("stateIdle", ConvertTask.STATE_IDLE); // STATE_IDLE = 0
return query.autoClose().list(ConvertTask.class);
```
and now have unhandled Exception:

018-05-22 19:21:36,554 [org.quartz.core.JobRunShell] [ERROR] - Job convert_task_group.convert_task_ns threw an unhandled Exception: 
jodd.proxetta.ProxettaException: Target missing
	at jodd.proxetta.ProxettaFactory.process(ProxettaFactory.java:211)
	at jodd.proxetta.ProxettaFactory.define(ProxettaFactory.java:266)
	at jodd.db.debug.BaseLoggableFactory.wrap(BaseLoggableFactory.java:85)
	at jodd.db.debug.LoggablePreparedStatementFactory.create(LoggablePreparedStatementFactory.java:55)
	at jodd.db.DbQueryBase.initializeJdbc(DbQueryBase.java:281)
	at jodd.db.DbQueryBase.init(DbQueryBase.java:199)
	at jodd.db.DbQuery.initPrepared(DbQuery.java:1244)
	at jodd.db.DbQuery.setInteger(DbQuery.java:227)
	at com.xxx.dao.ConvertTaskDao.findToHandleTasks(ConvertTaskDao.java:30)
	at com.xxx.dao.ConvertTaskDao$$Proxetta.findToHandleTasks$0(Unknown Source)
	at com.xxx.dao.ConvertTaskDao$$Proxetta.findToHandleTasks(Unknown Source)
	at com.xxx.job.ConvertScheduledJob.execute(ConvertScheduledJob.java:35)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
2018-05-22 19:21:36,585 [org.quartz.core.ErrorLogger] [ERROR] - Job (convert_task_group.convert_task_ns threw an exception.
org.quartz.SchedulerException: Job threw an unhandled exception. [See nested exception: jodd.proxetta.ProxettaException: Target missing]
	at org.quartz.core.JobRunShell.run(JobRunShell.java:213)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
Caused by: jodd.proxetta.ProxettaException: Target missing
	at jodd.proxetta.ProxettaFactory.process(ProxettaFactory.java:211)
	at jodd.proxetta.ProxettaFactory.define(ProxettaFactory.java:266)
	at jodd.db.debug.BaseLoggableFactory.wrap(BaseLoggableFactory.java:85)
	at jodd.db.debug.LoggablePreparedStatementFactory.create(LoggablePreparedStatementFactory.java:55)
	at jodd.db.DbQueryBase.initializeJdbc(DbQueryBase.java:281)
	at jodd.db.DbQueryBase.init(DbQueryBase.java:199)
	at jodd.db.DbQuery.initPrepared(DbQuery.java:1244)
	at jodd.db.DbQuery.setInteger(DbQuery.java:227)
	at com.xxx.dao.ConvertTaskDao.findToHandleTasks(ConvertTaskDao.java:30)
	at com.xxx.dao.ConvertTaskDao$$Proxetta.findToHandleTasks$0(Unknown Source)
	at com.xxx.dao.ConvertTaskDao$$Proxetta.findToHandleTasks(Unknown Source)
	at com.xxx.job.ConvertScheduledJob.execute(ConvertScheduledJob.java:35)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202)

**Comment by igr** [comment]
Which version of Java do you use?

**Comment by igr** [comment]
One more question: when quartz is running, does it see the `PreparedStatement` implementation class? Maybe the classloader of quartz does not see the JDBC drivers...

The best way to test this is to disable the `debug` mode and see if the query runs.

**Comment by titanseason** [comment]
Jodd version is 4.3.2
And I will try to disable debug mode

**Comment by igr** [comment]
Awesome, let me know the results!

**Comment by titanseason** [comment]
@igr If I disable debug mode, this exception won't happen.
Thank you

**Comment by igr** [comment]
Huh - it would be better if it did happen, cause I would be able to fix more easily :)

Would it be possible for you to enable debug again, and put a breakpoint here:

https://github.com/oblac/jodd/blob/master/jodd-db/src/main/java/jodd/db/debug/BaseLoggableFactory.java#L76

and checkout what is the `targetClass`? Because for some reason Jodd can't open the `InputStream` of that class.

**Comment by titanseason** [comment]
@igr it's `interface java.sql.PreparedStatement`
`Class<T>(interface java.sql.PreparedStatement)`

**Comment by titanseason** [comment]
@igr Thanks
I found out that this exception only happened once, the second time I execute the same task in quartz, none exception happened.

**Comment by titanseason** [comment]
```
public class WebApplication extends PetiteWebApp {

    private PetiteContainer petiteContainer;

    @Override
    public PetiteWebApp withPetiteContainer(Supplier<PetiteContainer> petiteContainerSupplier) {
        PetiteWebApp webApp = super.withPetiteContainer(petiteContainerSupplier);
        petiteContainer = petiteContainerSupplier.get();
        return webApp;
    }

    @Override
    protected void ready() {
        super.ready();
        ScheduledJobs.registerAll(petiteContainer);
    }
}
```
I register scheduled jobs in `WebApp#ready()` method

**Comment by igr** [comment]
Awesome @titanseason, this actually helps, will try it!

**Comment by igr** [comment]
Hey @titanseason I am not able to reproduce :(

For some reason, the class file for the `PreparedStatement` can not be read from the filesystem... If you are sure its related to the Quartz, maybe its too firing events too soon? Can you postpone?

I am really having no ideas whats going on... If you wish and have a code that you can send me privately, I would be happy to help.

**Comment by titanseason** [comment]
@igr I'm busy these days, you can close this issue first. And can you leave you email? Thus I can extract the example codes and send them to you when I am not busy.

**Comment by igr** [comment]
sure, if you can that would be awesome!

igor@jodd.org

**Comment by titanseason** [comment]
Now I known why, I overwrite the method `withPetiteContainer` of `PetiteWebApp`
```
    @Override
    public PetiteWebApp withPetiteContainer(Supplier<PetiteContainer> petiteContainerSupplier) {
        PetiteWebApp webApp = super.withPetiteContainer(petiteContainerSupplier);
        petiteContainer = petiteContainerSupplier.get();
        return webApp;
    }
```
and to get DAO with `ConvertTaskDao dao =petiteContainer.getBean(ConvertTaskDao.class);`, thus this exception happened.
Now I overwrite `PetiteWebApp#ready()` , and this exception won't happen
```
 @Override
    protected void ready() {
        super.ready();
        petiteContainer = madvocContainer.getPetiteContainer().getBean(PETITE_CONTAINER_NAME);
        ConvertTaskDao dao =petiteContainer.getBean(ConvertTaskDao.class);
    }
```
