### ISSUE TITLE
@Transaction annotation no effect on supper class

### ISSUE THREAD

**Issue by yujinping** [oblac/jodd#613]
When using UserService in UserAction,there is exception 
```
Caused by:
jodd.db.DbSqlException: No transaction is in progress and DbSession can't be provided. It seems that transaction manager is not used to begin a transaction.
	at jodd.db.jtx.DbJtxSessionProvider.getDbSession(DbJtxSessionProvider.java:62)
	at jodd.db.DbQueryBase.initSession(DbQueryBase.java:220)
	at jodd.db.DbQuery.<init>(DbQuery.java:88)
	at jodd.db.DbQuery.<init>(DbQuery.java:98)
	at jodd.db.oom.DbOomQuery.<init>(DbOomQuery.java:113)
	at jodd.db.oom.DbOomQuery.query(DbOomQuery.java:117)
	at jodd.db.oom.dao.GenericDao.findById(GenericDao.java:196)
	at io.github.yujinping.jodd.demo.dao.BaseDao.findById(BaseDao.java:91)
	at io.github.yujinping.jodd.demo.service.BaseService.get(BaseService.java:31)
	at io.github.yujinping.jodd.demo.action.api.UserAction.test(UserAction.java:22)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at jodd.madvoc.ActionRequest.invokeActionMethod(ActionRequest.java:252)
	at jodd.madvoc.ActionRequest.lambda$createExecutionArray$1(ActionRequest.java:223)
	at jodd.madvoc.ActionRequest.invoke(ActionRequest.java:237)
	at jodd.madvoc.interceptor.ServletConfigInterceptor.intercept(ServletConfigInterceptor.java:73)
	at jodd.madvoc.interceptor.ActionInterceptor.apply(ActionInterceptor.java:38)
	at jodd.madvoc.ActionRequest.invoke(ActionRequest.java:237)
	at jodd.joy.i18n.I18nInterceptor.intercept(I18nInterceptor.java:46)
	at jodd.madvoc.interceptor.ActionInterceptor.apply(ActionInterceptor.java:38)
	at jodd.madvoc.ActionRequest.invoke(ActionRequest.java:237)
	at jodd.madvoc.ActionRequest.lambda$createExecutionArray$0(ActionRequest.java:206)
	at jodd.madvoc.ActionRequest.invoke(ActionRequest.java:237)
	at jodd.madvoc.component.MadvocController.invoke(MadvocController.java:154)
	at jodd.madvoc.MadvocServletFilter.doFilter(MadvocServletFilter.java:108)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1759
```

code  like this:

BaseDao.java
```
@PetiteBean
public class BaseDao<T> {
    private static final Logger logger = LoggerFactory.getLogger(BaseDao.class);
    @PetiteInject
    AppDao appDao;
    public T findById(Class<T> glass, Long id) {
        return appDao.findById(glass, id);
    }
}
```

BaseService.java
```
@PetiteBean
public class BaseService<T> {
    @PetiteInject
    BaseDao<T> baseDao;
    
    @ReadWriteTransaction
    public void save(T object){
        baseDao.save(object);
    }
    
    @ReadWriteTransaction
    public void update(T object){
        baseDao.update(object);
    }
    
    @ReadWriteTransaction
    public void remove(Class<T> glass,Long id){
        baseDao.remove(glass,id);
    }
    
    @Transaction
    public T get(Class<T> glass,Long id){
        return baseDao.findById(glass,id);
    }
}

```
UserService.java
```
@PetiteBean
public class UserService extends BaseService<User>{
}
```
UserAction.java
```
@MadvocAction("/users")
public class UserAction extends BaseAction {
    @PetiteInject
    UserService userService;

    @RestAction("{id}")
    @GET
    public JsonResult test(@In Long id){
        return JsonResult.of(userService.get(User.class,id));
    }
}

```

run the jetty server and visit http://localhost/users/1 
then throws jodd.db.DbSqlException

It seems that the annotation on UserService's supper class BaseService is no effect for DbOomManager,this is not expected.
Is this a bug? or wrong code of mine ?
Jodd version: 4.3.2

**Comment by yujinping** [comment]
When using BaseService to fetch the user entity,everything is fine!
UserAction.java
```

@MadvocAction("/users")
public class UserAction extends BaseAction {
    @PetiteInject
    UserService userService;
    @PetiteInject
    BaseService<User> baseService;

    @RestAction("{id}")
    @GET
    public JsonResult test(@In Long id){
        return JsonResult.of(userService.get(User.class,id));
    }

    @RestAction("test/{id}")
    @GET
    public JsonResult test2(@In Long id){
        return JsonResult.of(baseService.get(User.class,id));
    }
}
```

**Comment by igr** [comment]
That is true, that is how the TX aspect is registered:

```
		return new ProxyAspect(
			AnnotationTxAdvice.class,
			((ProxyPointcut)
				methodInfo -> methodInfo.isPublicMethod() && methodInfo.isTopLevelMethod())
				.and(MethodWithAnnotationPointcut.of(annotations))
		);

```

You see the `methodInfo.isTopLevelMethod()` :)

But you are right, this is too strict.

**Comment by igr** [comment]
I am patching it now... I just realized there is no trivial way for you to change this in the runtime, only by patching the Jodd by yourself :(

I will address this issue as well!

**Comment by yujinping** [comment]
@igr thanks! Our team is using jodd 3.6.7,and want to upgrade to 4.3.2 or higher.
 As the above code of mine,if annotation declare in super class are effective,then the  code lines of the Service would be less more.  It's fine for writing and maintainable.

**Comment by igr** [comment]
Nice!

Maybe you can wait for v5 - there will be some more features added.
Hopefully soon!
