### ISSUE TITLE
java.lang.NoClassDefFoundError: T,Seem that Proxy cannot pass generic type to the target class!

### ISSUE THREAD

**Issue by yujinping** [oblac/jodd#616]
hi @igr 
When I use UserDao to store User info to database,the exception is:
```
8821 [DEBUG] j.m.c.MadvocController.invoke:103 - Action path: GET /users/store
8821 [DEBUG] j.m.c.MadvocController.invoke:116 - Invoking action path '/users/store' using io.github.yujinping.mall.action.api.UserAction#store
8837 [DEBUG] j.j.i.LocalizationUtil.setRequestBundleName:79 - Bundle name for this request: io.github.yujinping.mall.action.api.UserAction
8880 [DEBUG] j.j.JtxTransactionManager.requestTransaction:273 - Requesting TX jtx{Required,readwrite,Default,-1}
8882 [DEBUG] j.j.JtxTransaction.<init>:102 - New JTX {status:Active, mode:jtx{Required,readwrite,Default,-1}}
8905 [DEBUG] j.d.j.DbJtxSessionProvider.getDbSession:57 - Requesting db TX manager session
8905 [DEBUG] j.d.DbSession.<init>:67 - Creating new db session
8906 [DEBUG] j.d.j.DbJtxResourceManager.beginTransaction:71 - begin jtx
8907 [DEBUG] j.d.DbSession.beginTransaction:248 - Beginning transaction
9035 [DEBUG] j.d.DbQueryBase.executeUpdate:761 - Executing update: insert into users (level, password, register_time, username) values (?, ?, ?, ?)
9036 [DEBUG] j.d.DbQueryBase.executeUpdate:786 - execution time: 116ms
9037 [DEBUG] j.j.w.LeanJtxWorker.maybeCommitTransaction:93 - commit tx
9037 [DEBUG] j.j.JtxTransaction.commitOrRollback:255 - Commit JTX
9037 [DEBUG] j.d.j.DbJtxResourceManager.commitTransaction:83 - commit jtx
9037 [DEBUG] j.d.DbSession.commitTransaction:267 - Committing transaction
9089 [DEBUG] j.d.DbSession.closeSession:90 - Closing db session
11:14:14.477 [qtp1277181601-17] INFO  i.g.y.mall.service.UserService - Call service save success!
9097 [ERROR] j.m.MadvocServletFilter.doFilter:110 - Invoking action path failed: /users/store
java.lang.RuntimeException: java.lang.NoClassDefFoundError: T
	at jodd.exception.ExceptionUtil.wrapToException(ExceptionUtil.java:280)
	at jodd.madvoc.ActionRequest.invokeActionMethod(ActionRequest.java:254)
	at jodd.madvoc.ActionRequest.lambda$createExecutionArray$1(ActionRequest.java:223)
	at jodd.madvoc.ActionRequest.invoke(ActionRequest.java:237)
	at jodd.madvoc.interceptor.ServletConfigInterceptor.intercept(ServletConfigInterceptor.java:73)
	at jodd.madvoc.interceptor.ActionInterceptor.apply(ActionInterceptor.java:38)
	at jodd.madvoc.ActionRequest.invoke(ActionRequest.java:237)
	at jodd.joy.i18n.I18nInterceptor.intercept(I18nInterceptor.java:46)
	at jodd.madvoc.interceptor.ActionInterceptor.apply(ActionInterceptor.java:38)
	at jodd.madvoc.ActionRequest.invoke(ActionRequest.java:237)
	at jodd.madvoc.ActionRequest.lambda$createExecutionArray$0(ActionRequest.java:206)
	at jodd.madvoc.ActionRequest.invoke(ActionRequest.java:237)
	at jodd.madvoc.component.MadvocController.invoke(MadvocController.java:154)
	at jodd.madvoc.MadvocServletFilter.doFilter(MadvocServletFilter.java:108)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1751)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:582)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1180)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:512)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1112)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:213)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:119)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134)
	at org.eclipse.jetty.server.Server.handle(Server.java:534)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:333)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:283)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:108)
	at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.executeProduceConsume(ExecuteProduceConsume.java:303)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:148)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:136)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NoClassDefFoundError: T
	at io.github.yujinping.mall.dao.UserDao$$Proxetta.store$0(Unknown Source)
	at io.github.yujinping.mall.dao.UserDao$$Proxetta.store(Unknown Source)
	at io.github.yujinping.mall.service.UserService.register(UserService.java:24)
	at io.github.yujinping.mall.action.api.UserAction.store(UserAction.java:44)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at jodd.madvoc.ActionRequest.invokeActionMethod(ActionRequest.java:252)
	... 37 more
Caused by: java.lang.ClassNotFoundException: T
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.eclipse.jetty.webapp.WebAppClassLoader.loadClass(WebAppClassLoader.java:487)
	at org.eclipse.jetty.webapp.WebAppClassLoader.loadClass(WebAppClassLoader.java:428)
	... 46 more
```

Using jodd 4.3.2 and I hack the source code of JoddJoy JoyProxetta.java as the following to let the annotation effect on super class :

```
	protected ProxyAspect createTxProxyAspects() {
		return new ProxyAspect(
			AnnotationTxAdvice.class,
			((ProxyPointcut)
				**methodInfo -> methodInfo.isPublicMethod())**
				.and(MethodWithAnnotationPointcut.of(JoddJtx.defaults().getTxAnnotations()))
		);
	}
```
After this,wrote the following code 
**BaseDao.java**
```
@PetiteBean
public class BaseDao<T> {
    @PetiteInject
    AppDao appDao;

    @ReadWriteTransaction
    public void store(T o) {
        appDao.store(o);
    }
}
```
**User.java**
```
@DbTable("users")
public class User extends BaseEntity{
    @DbColumn
    private String username = null; //
    @DbColumn
    private String password = null; //
    @DbColumn
    private Integer level = 0;
    @DbColumn
    private LocalDateTime registerTime = LocalDateTime.now();
    //Getter and Setter ...
}
```

**UserDao.java**
```
@PetiteBean
public class UserDao extends BaseDao<User> {
}

```

**UserService.java**
```
@PetiteBean
public class UserService extends BaseService<User>{
    private static final Logger logger = LoggerFactory.getLogger(UserService.class);
    @PetiteInject
    UserDao userDao;

    //@ReadWriteTransaction
    public User register(String username,String password){
        User user = new User();
        user.setUsername(username);
        user.setPassword(password);
        super.save(user);
        logger.info("Call service save success!");//This code can store the user
        userDao.store(user);//And this cause the exception
        logger.info("Call dao save success!");
//        if(user!=null)
//            throw new RuntimeException("Test for transaction , Oops!");
        return user;
    }
}
```
**UserAction.java**
```
@MadvocAction("/users")
public class UserAction extends BaseAction {
    @PetiteInject
    UserService userService;
    @PetiteInject
    UserDao userDao;

    @RestAction("store")
    @GET
    public JsonResult store(@In String username,@In String password){
        User user = userService.register(username,password);
        return JsonResult.of(user);
    }
}
```
visit http://localhost:8080/users/store?username=a&password=b
the exception happend!

**Seem that Proxy cannot pass generic type to the target class!**

**Comment by igr** [comment]
![image](https://user-images.githubusercontent.com/2280001/41068382-7fc1c67e-69e9-11e8-8486-a4fa97bd2fe1.png)

**Comment by igr** [comment]
Thank you for awesomely detailed example! We had an aerror with supertypes and reading wrong generics. It's fixed now, hopefully :)

Trually appreciate your support!

**Comment by yujinping** [comment]
thanks for your hard work!

**Comment by yujinping** [comment]
@igr After clone the master branch and compile it ,I cannot find jodd.joy.db.AppDao.java.
Is there a replacement of it? So the demo which I provided could not pass the compiler's check!

**Comment by igr** [comment]
Sorry for not explaining - it was too late last night...

## AppDao

`AppDao` was this:

```
public class AppDao extends GenericDao {
	@PetiteInject
	protected DbIdGenerator dbIdGenerator;
	@Override
	protected long generateNextId(final DbEntityDescriptor ded) {
		return dbIdGenerator.nextId(ded.getType());
	}
}
```

Unfortunately, the quality of the `DbIdGenerator` was low. We would need to make a better one - and its plan, just don't know if we can make it in this release.

_Workaround_: if you don't use the `DbIdGenerator`, just make dummy:

```
@PetiteBean
public class AppDao extends GenericDao {}
```

## The issue

Workaround for the issue is to either:

1. override the public methods of `GenericDao`; or
2. Have the `UserDao` to wrap the `GenericDao` i.e. `AppDao`:

```
public class UserDao {

@PetiteInject AppDao appDao;
// wrapper
```

The good thing is that you can generate this code in Intellij IDEA very easy.


## Finally...

Sorry for not being able to release fixes for `4.x`. I am finalizing the version 5; and it comes with many new and nice things. I am just doing some final testing with it, and should be released very soon.

**Comment by yujinping** [comment]
I use the master code to refactor my demo project! and use the AppDao wrapper code. But I found some difference of AppDao and have exception runtime.
My AppDao.java
```
package io.github.yujinping.mall.dao;

import jodd.db.DbOom;
import jodd.db.oom.dao.GenericDao;
import jodd.petite.meta.PetiteBean;

@PetiteBean
public class AppDao extends GenericDao {
    public AppDao(DbOom dbOom) {
        super(dbOom);
    }
}

``` 
**Cause GenericDao has no default constructor(none arguments)**
the exception:
```
Caused by:
javax.servlet.ServletException: jodd.petite.PetiteException: Failed to create new bean instance 'io.github.yujinping.mall.dao.AppDao' using constructor: public io.github.yujinping.mall.dao.AppDao(jodd.db.DbOom); <--- java.lang.IllegalArgumentException: wrong number of arguments
	at jodd.madvoc.MadvocServletFilter.doFilter(MadvocServletFilter.java:112)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1751)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:582)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1180)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:512)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1112)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:213)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:119)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134)
	at org.eclipse.jetty.server.Server.handle(Server.java:534)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:333)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:283)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:108)
	at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.executeProduceConsume(ExecuteProduceConsume.java:303)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:148)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:136)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589)
	at java.lang.Thread.run(Thread.java:748)
Caused by: jodd.petite.PetiteException: Failed to create new bean instance 'io.github.yujinping.mall.dao.AppDao' using constructor: public io.github.yujinping.mall.dao.AppDao(jodd.db.DbOom); <--- java.lang.IllegalArgumentException: wrong number of arguments
	at jodd.petite.BeanData.newBeanInstance(BeanData.java:159)
	at jodd.petite.BeanData.<init>(BeanData.java:62)
	at jodd.petite.PetiteContainer.getBean(PetiteContainer.java:161)
	at jodd.petite.PetiteContainer.getBean(PetiteContainer.java:122)
	at jodd.petite.PetiteContainer.lookupMixingScopedBean(PetiteContainer.java:94)
	at jodd.petite.BeanData.wireProperties(BeanData.java:219)
	at jodd.petite.BeanData.wireBean(BeanData.java:210)
	at jodd.petite.PetiteContainer.registerBeanAndWireAndInjectParamsAndInvokeInitMethods(PetiteContainer.java:216)
	at jodd.petite.PetiteContainer.getBean(PetiteContainer.java:162)
	at jodd.petite.PetiteContainer.getBean(PetiteContainer.java:122)
	at jodd.petite.PetiteContainer.lookupMixingScopedBean(PetiteContainer.java:94)
	at jodd.petite.BeanData.wireProperties(BeanData.java:219)
	at jodd.petite.BeanData.wireBean(BeanData.java:210)
	at jodd.petite.PetiteContainer.registerBeanAndWireAndInjectParamsAndInvokeInitMethods(PetiteContainer.java:216)
	at jodd.petite.PetiteContainer.createBean(PetiteContainer.java:300)
	at jodd.petite.PetiteContainer.createBean(PetiteContainer.java:286)
	at jodd.madvoc.petite.PetiteMadvocController.createAction(PetiteMadvocController.java:46)
	at jodd.madvoc.component.MadvocController.invoke(MadvocController.java:173)
	at jodd.madvoc.MadvocServletFilter.doFilter(MadvocServletFilter.java:108)
	... 25 more
Caused by: java.lang.IllegalArgumentException: wrong number of arguments
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at jodd.petite.BeanData.newBeanInstance(BeanData.java:157)
	... 43 more
```

**Comment by igr** [comment]
Ok, let me explain:

```
@PetiteBean
public class AppDao extends GenericDao {
    public AppDao() {
        super(DbOom.get());
    }
}
```

The `DbOom` is the central place for a single database. When only one database is set, you can use `DbOom.get()` or simply use Db as before - it is all configured to work like before when only one database is set.

Now in this case you have to set the DbOom first.

But let me do the example for you for joddframework.org - I am doing it anyway, so we let me do it and share with you!

**Comment by yujinping** [comment]
thx @igr .
After use DbOom.get() method, the console cannot find any exception!
But when visit http://localhost:8080/users/store?username=a&password=b
no data insert into the database, 
and the output json of web is not expect
JSON:
```

{"cause":null,"details":["jodd.db.jtx.DbJtxSessionProvider.getDbSession(DbJtxSessionProvider.java:62)","jodd.db.DbQueryBase.initSession(DbQueryBase.java:216)","jodd.db.DbQuery.<init>(DbQuery.java:115)","jodd.db.DbQuery.<init>(DbQuery.java:125)","jodd.db.oom.DbOomQuery.<init>(DbOomQuery.java:129)","jodd.db.oom.DbOomQuery.query(DbOomQuery.java:135)","jodd.db.oom.dao.GenericDao.store(GenericDao.java:99)","io.github.yujinping.mall.dao.BaseDao.save(BaseDao.java:148)","io.github.yujinping.mall.service.BaseService.save(BaseService.java:16)","io.github.yujinping.mall.service.UserService.register(UserService.java:21)","io.github.yujinping.mall.action.api.UserAction.store(UserAction.java:44)","sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)","sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)","sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)","java.lang.reflect.Method.invoke(Method.java:498)","jodd.madvoc.ActionRequest.invokeActionMethod(ActionRequest.java:256)","jodd.madvoc.ActionRequest.lambda$createExecutionArray$1(ActionRequest.java:226)","jodd.madvoc.ActionRequest.invoke(ActionRequest.java:240)","jodd.madvoc.interceptor.ServletConfigInterceptor.intercept(ServletConfigInterceptor.java:74)","jodd.madvoc.interceptor.ActionInterceptor.apply(ActionInterceptor.java:38)","jodd.madvoc.ActionRequest.invoke(ActionRequest.java:240)","jodd.joy.i18n.I18nInterceptor.intercept(I18nInterceptor.java:46)","jodd.madvoc.interceptor.ActionInterceptor.apply(ActionInterceptor.java:38)","jodd.madvoc.ActionRequest.invoke(ActionRequest.java:240)","jodd.joy.auth.AuthInterceptor.intercept(AuthInterceptor.java:101)","jodd.madvoc.interceptor.ActionInterceptor.apply(ActionInterceptor.java:38)","jodd.madvoc.ActionRequest.invoke(ActionRequest.java:240)","jodd.madvoc.interceptor.JsonErrorInterceptor.intercept(JsonErrorInterceptor.java:38)","jodd.madvoc.interceptor.ActionInterceptor.apply(ActionInterceptor.java:38)","jodd.madvoc.ActionRequest.invoke(ActionRequest.java:240)","jodd.madvoc.ActionRequest.lambda$createExecutionArray$0(ActionRequest.java:209)","jodd.madvoc.ActionRequest.invoke(ActionRequest.java:240)","jodd.madvoc.component.MadvocController.invoke(MadvocController.java:188)","jodd.madvoc.MadvocServletFilter.doFilter(MadvocServletFilter.java:108)","org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1751)","org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:582)","org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)","org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)","org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226)","org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1180)","org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:512)","org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)","org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1112)","org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)","org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:213)","org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:119)","org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134)","org.eclipse.jetty.server.Server.handle(Server.java:534)","org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:333)","org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251)","org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:283)","org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:108)","org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93)","org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.executeProduceConsume(ExecuteProduceConsume.java:303)","org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:148)","org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:136)","org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671)","org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589)","java.lang.Thread.run(Thread.java:748)"],"message":"No transaction is in progress and DbSession can't be provided. It seems that transaction manager is not used to begin a transaction.","error":"jodd.db.DbSqlException"}
```

**Comment by igr** [comment]
Yes, because you need to set up the database now first. Let me make an example for you, please :) I will paste the link here

**Comment by igr** [comment]
Hey @yujinping!

Very close to the release :)

See: https://github.com/oblac/tutorial/tree/v5

This is an updated tutorial of the http://joddframework.org

You can just go to step #6, as it is the most complete one.

Also it makes sense to take a look at the JodJoy integration tests.

**Comment by igr** [comment]
Hope you gonna like it!
