### ISSUE TITLE
emailSender

### ISSUE THREAD

**Issue by HugoResende** [oblac/jodd#626]
package emailSender;

import org.apache.commons.mail.EmailException;
import org.apache.commons.mail.SimpleEmail;

public class sendEmail {
	
	private static void sendEmail(PojoEmail objEmail)   {
        SimpleEmail email = new SimpleEmail(); // cria um novo objeto email
        email.setHostName("smtp.gmail.com");//troca o nome do host smtp
        email.setSmtpPort(465); // porta de acordo com o host smtp
        try {
            email.addTo(objEmail.getEmailDestinatario()); // destinatario do email
        } catch (EmailException e) {
            e.printStackTrace();
        }
        try {
            email.setFrom("email@gmail.com", "Title"); // remetente
        } catch (EmailException e) {
            e.printStackTrace();
        }
        email.setSubject(objEmail.getAssunto()); // assunto do email
        try {
            email.setMsg(objEmail.getMensagem()); // mensagem do email
        } catch (EmailException e) {
            e.printStackTrace();
        }
        email.setSSL(true);
        email.setAuthentication("email@gmail.com", "senha"); // email e senha do remetente
        email.setDebug(true);
        try {
            email.send(); // envia o email
            System.out.println("Successfully sent to "+objEmail.getEmailDestinatario());
        } catch (EmailException e) {
            e.printStackTrace();
        }  
    }

	public void Spam(PojoEmail objEmail) {
		sendEmail(objEmail);	
	}
}
//Error
Eu tentei executar esse seguinte código para estar enviando email, mas o resultado saiu dessa maneira:
DEBUG: JavaMail version 1.6.1
DEBUG: successfully loaded resource: /META-INF/javamail.default.providers
DEBUG: Tables of loaded providers
DEBUG: Providers Listed By Class Name: {com.sun.mail.smtp.SMTPSSLTransport=javax.mail.Provider[TRANSPORT,smtps,com.sun.mail.smtp.SMTPSSLTransport,Oracle], com.sun.mail.smtp.SMTPTransport=javax.mail.Provider[TRANSPORT,smtp,com.sun.mail.smtp.SMTPTransport,Oracle], com.sun.mail.imap.IMAPSSLStore=javax.mail.Provider[STORE,imaps,com.sun.mail.imap.IMAPSSLStore,Oracle], com.sun.mail.pop3.POP3SSLStore=javax.mail.Provider[STORE,pop3s,com.sun.mail.pop3.POP3SSLStore,Oracle], com.sun.mail.imap.IMAPStore=javax.mail.Provider[STORE,imap,com.sun.mail.imap.IMAPStore,Oracle], com.sun.mail.pop3.POP3Store=javax.mail.Provider[STORE,pop3,com.sun.mail.pop3.POP3Store,Oracle]}
DEBUG: Providers Listed By Protocol: {imaps=javax.mail.Provider[STORE,imaps,com.sun.mail.imap.IMAPSSLStore,Oracle], imap=javax.mail.Provider[STORE,imap,com.sun.mail.imap.IMAPStore,Oracle], smtps=javax.mail.Provider[TRANSPORT,smtps,com.sun.mail.smtp.SMTPSSLTransport,Oracle], pop3=javax.mail.Provider[STORE,pop3,com.sun.mail.pop3.POP3Store,Oracle], pop3s=javax.mail.Provider[STORE,pop3s,com.sun.mail.pop3.POP3SSLStore,Oracle], smtp=javax.mail.Provider[TRANSPORT,smtp,com.sun.mail.smtp.SMTPTransport,Oracle]}
DEBUG: successfully loaded resource: /META-INF/javamail.default.address.map
DEBUG: getProvider() returning javax.mail.Provider[TRANSPORT,smtp,com.sun.mail.smtp.SMTPTransport,Oracle]
DEBUG SMTP: need username and password for authentication
DEBUG SMTP: protocolConnect returning false, host=smtp.gmail.com, user=usuario, password=<null>
DEBUG SMTP: useEhlo true, useAuth true
DEBUG SMTP: trying to connect to host "smtp.gmail.com", port 465, isSSL false
org.apache.commons.mail.EmailException: Sending the email to the following server failed : smtp.gmail.com:465
	at org.apache.commons.mail.Email.sendMimeMessage(Email.java:1469)
	at org.apache.commons.mail.Email.send(Email.java:1496)
	at emailSender.sendEmail.sendEmail(sendEmail.java:32)
	at emailSender.sendEmail.Spam(sendEmail.java:40)
	at emailSender.Main.main(Main.java:13)
Caused by: com.sun.mail.util.MailConnectException: Couldn't connect to host, port: smtp.gmail.com, 465; timeout 60000;
  nested exception is:
	java.net.ConnectException: Connection refused: connect
	at com.sun.mail.smtp.SMTPTransport.openServer(SMTPTransport.java:2209)
	at com.sun.mail.smtp.SMTPTransport.protocolConnect(SMTPTransport.java:740)
	at javax.mail.Service.connect(Service.java:388)
	at javax.mail.Service.connect(Service.java:246)
	at javax.mail.Service.connect(Service.java:195)
	at javax.mail.Transport.send0(Transport.java:254)
	at javax.mail.Transport.send(Transport.java:124)
	at org.apache.commons.mail.Email.sendMimeMessage(Email.java:1459)
	... 4 more
Caused by: java.net.ConnectException: Connection refused: connect
	at java.net.DualStackPlainSocketImpl.waitForConnect(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(Unknown Source)
	at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source)
	at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source)
	at java.net.AbstractPlainSocketImpl.connect(Unknown Source)
	at java.net.PlainSocketImpl.connect(Unknown Source)
	at java.net.SocksSocketImpl.connect(Unknown Source)
	at java.net.Socket.connect(Unknown Source)
	at com.sun.mail.util.SocketFetcher.createSocket(SocketFetcher.java:351)
	at com.sun.mail.util.SocketFetcher.getSocket(SocketFetcher.java:218)
	at com.sun.mail.smtp.SMTPTransport.openServer(SMTPTransport.java:2175)
	... 11 more

Alguem poderia me ajudar?

**Comment by neroux** [comment]
> java.net.ConnectException: Connection refused: connect

should be pretty self-explanatory

**Comment by HugoResende** [comment]
Sorry, I don't understand.

**Comment by igr** [comment]
When talking to Gmail you need to do more things.

See: https://jodd.org/email/faq.html#cant-access-gmail

In your case, the connection simply is rejected by the target server - nothing we can do here, sorry.
