### ISSUE TITLE
Jodd crashes on Java 11

### ISSUE THREAD

**Issue by slandelle** [oblac/jodd#654]
## Current behavior

jodd-json and csselly crash under Java 11:

```
java.lang.StringIndexOutOfBoundsException: begin 0, end -1, length 2
	at java.base/java.lang.String.checkBoundsBeginEnd(String.java:3319)
	at java.base/java.lang.String.substring(String.java:1874)
	at jodd.system.JavaInfo.detectJavaVersionNumber(JavaInfo.java:159)
	at jodd.system.JavaInfo.<init>(JavaInfo.java:34)
	at jodd.system.JvmInfo.<init>(JvmInfo.java:28)
	at jodd.system.OsInfo.<init>(OsInfo.java:30)
	at jodd.system.RuntimeInfo.<init>(RuntimeInfo.java:32)
	at jodd.system.UserInfo.<init>(UserInfo.java:35)
	at jodd.system.SystemInfo.<init>(SystemInfo.java:28)
	at jodd.system.SystemUtil.<clinit>(SystemUtil.java:129)
```

## Expected behavior

Jodd supports Java 11

## Steps to Reproduce the Problem

```
$ java -version
openjdk version "11" 2018-09-25
OpenJDK Runtime Environment AdoptOpenJDK (build 11+28-201810021910)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11+28-201810021910, mixed mode)
```

Try to load `jodd.csselly.CSSelly` class, exception happens in static initializer.

**Comment by slandelle** [comment]
PR upcoming
