### ISSUE TITLE
Proxetta - Methref: interfaces not supported

### ISSUE THREAD

**Issue by jmini** [oblac/jodd#665]
## Current behavior

It is not possible to use [`Methref`](https://jodd.org/ref/methref.html) with interfaces, it works only for classes.

## Expected behavior

It would be great if `Methref` could work with interfaces.

## Steps to Reproduce the Problem

Sample demo:

```java
package tmp;

import jodd.methref.Methref;

public class Main {
    public static interface Str {
        public void boo();
    }
    public static void main(String[] args) {
        Methref<Str> m = Methref.on(Str.class);  // create Methref tool

        // example #1
        m.to().boo();
        String n = m.ref();                      // returns String: 'boo'
        System.out.println(n);
    }
}
```

Exception:

```
Exception in thread "main" jodd.proxetta.ProxettaException: Unable to process abstract method: tmp/Main$Str#boo()V
	at jodd.proxetta.asm.ProxettaClassBuilder.applyProxy(ProxettaClassBuilder.java:305)
	at jodd.proxetta.asm.ProxettaClassBuilder.visitMethod(ProxettaClassBuilder.java:140)
	at jodd.asm7.ClassReader.readMethod(ClassReader.java:1113)
	at jodd.asm7.ClassReader.accept(ClassReader.java:679)
	at jodd.asm7.ClassReader.accept(ClassReader.java:391)
	at jodd.proxetta.impl.ProxyProxettaFactory.process(ProxyProxettaFactory.java:74)
	at jodd.proxetta.ProxettaFactory.process(ProxettaFactory.java:232)
	at jodd.proxetta.ProxettaFactory.define(ProxettaFactory.java:267)
	at jodd.methref.MethrefProxetta.defineProxy(MethrefProxetta.java:57)
	at jodd.methref.Methref.<init>(Methref.java:58)
	at jodd.methref.Methref.on(Methref.java:80)
	at tmp.Main.main(Main.java:10)
```

**Comment by igr** [comment]
This is true; it's a limitation of the `Proxetta` that can't make a proxy from an abstract class.

I have to think if this is a bug or a feature :)))

**Comment by igr** [comment]
I can maybe implement abstract methods with dummy implementation that returns `null`/`0`/`false`, depending of the returning type.

**Comment by igr** [comment]
This might be the longest issue I ever had. Sorry for that, bumpy ride.
