### ISSUE TITLE
java.lang.NumberFormatException: For input string: "9-Ubuntu" 

### ISSUE THREAD

**Issue by caraboides** [oblac/jodd#675]
## Current behavior

java.lang.NumberFormatException: For input string: "9-Ubuntu"
	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.base/java.lang.Integer.parseInt(Integer.java:652)
	at java.base/java.lang.Integer.parseInt(Integer.java:770)
	at jodd.system.JavaInfo.detectJavaVersionNumber(JavaInfo.java:159)

Under Ubuntu linux: 
```
java -version
openjdk version "9-Ubuntu"
OpenJDK Runtime Environment (build 9-Ubuntu+0-9b181-4)
OpenJDK 64-Bit Server VM (build 9-Ubuntu+0-9b181-4, mixed mode)
```

## Expected behavior

no Exception

## Steps to Reproduce the Problem

System.setProperty("java.version", "9-Ubuntu")
an then call jodd.system.JavaInfo.detectJavaVersionNumber

## Workaround
System.setProperty("java.version", "9")

**Comment by igr** [comment]
Thank you!!!! Small, but important fix!
