### ISSUE TITLE
http (v5.0.4) with proxy ,  timeout does not work

### ISSUE THREAD

**Issue by djxhero** [oblac/jodd#681]
"taskExecutor-49" #370 prio=5 os_prio=0 tid=0x00007fb66c087000 nid=0x1ae runnable [0x00007fb63e571000]
   java.lang.Thread.State: RUNNABLE
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
	at java.net.SocketInputStream.read(SocketInputStream.java:171)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at java.net.SocketInputStream.read(SocketInputStream.java:224)
	at jodd.http.net.HTTPProxySocketFactory.createHttpProxySocket(HTTPProxySocketFactory.java:104)
	at jodd.http.net.HTTPProxySocketFactory.createSocket(HTTPProxySocketFactory.java:55)
	at jodd.http.net.SocketHttpConnectionProvider.createSocket(SocketHttpConnectionProvider.java:139)
	at jodd.http.net.SocketHttpConnectionProvider.createHttpConnection(SocketHttpConnectionProvider.java:109)
	at jodd.http.HttpRequest.open(HttpRequest.java:753)
	at jodd.http.HttpRequest.open(HttpRequest.java:740)
	at jodd.http.HttpRequest._send(HttpRequest.java:859)
	at jodd.http.HttpRequest.send(HttpRequest.java:831)
	at com.shangde.info.management.util.IpProxyUtil.checkProxy(IpProxyUtil.java:113)

   Locked ownable synchronizers:
	- <0x00000000ee7d79c8> (a java.util.concurrent.ThreadPoolExecutor$Worker)

----------------------------------------------------------------------------------------------
**_socketRead0 won't return and keeps waiting_**
--------------------------------------------------------------------------------------------
Usage :
```java
public static boolean checkProxy(String ip, String port) {
        try {

            SocketHttpConnectionProvider scp = new SocketHttpConnectionProvider();
            int httpPort = port == null ? 80 : Integer.valueOf(port);

            scp.useProxy(ProxyInfo.httpProxy(ip, httpPort, null, null));
            Proxy proxy = new Proxy(Proxy.Type.HTTP, new InetSocketAddress(ip, httpPort));

            HttpResponse response = HttpRequest
                        .get("http://ping.chinaz.com/")
                        .timeout(30000)
                        .withConnectionProvider(scp)
                        .send();
      
            Boolean result = response != null && response.statusCode() == 200;
            if (result) {
                logger.info("checkProxy ok {}:{}", ip, port);
            }
            return result;
        } catch (Exception e) {
            logger.error("checkProxy fail {}:{}", ip, port);
        }
        return false;

    }
```

**Comment by igr** [comment]
Did you try to set `connectionTimeout()` too?

**Comment by igr** [comment]
Ah, ok, I figured :) Fix is on the way.

**Comment by igr** [comment]
What I did is to add `connectionTimeout` to the proxy sockets. The `timeout` is set _after_ the socket is connected, hence here you should use the `connectionTimeout`.

After this, there is nothing more I can do... and behavior depends on the underlying implementation.

**Comment by djxhero** [comment]
Thank you!
