### ISSUE TITLE
findById error when sql debug mode is opened!

### ISSUE THREAD

**Issue by yujinping** [oblac/jodd#682]
Jodd Joy 5.0.8

After enable DbOom sql debug mode!
```java
        DbOom om = DbOom.get();
        om.queryConfig().setDebug(showDebugSql);
```
then call 
```java
    genericDao.findById(User.class,1L);
```
Exception here:
```
12:25:55.768 [qtp1564984895-17] INFO  io.github.joy.hotel.service.LoginService - adminId=1
java.lang.ArrayIndexOutOfBoundsException: 6
	at jodd.asm7.ClassReader.readShort(ClassReader.java:3365)
	at jodd.asm7.ClassReader.<init>(ClassReader.java:182)
	at jodd.asm7.ClassReader.<init>(ClassReader.java:166)
	at jodd.asm7.ClassReader.<init>(ClassReader.java:152)
	at jodd.asm7.ClassReader.<init>(ClassReader.java:273)
	at jodd.proxetta.ProxettaFactory.process(ProxettaFactory.java:217)
	at jodd.proxetta.ProxettaFactory.define(ProxettaFactory.java:267)
	at jodd.db.debug.BaseLoggableFactory.wrap(BaseLoggableFactory.java:85)
	at jodd.db.debug.LoggablePreparedStatementFactory.create(LoggablePreparedStatementFactory.java:55)
	at jodd.db.DbQueryBase.initializeJdbc(DbQueryBase.java:292)
	at jodd.db.DbQueryBase.init(DbQueryBase.java:208)
	at jodd.db.DbQueryBase.execute(DbQueryBase.java:672)
	at jodd.db.DbQuery.execute(DbQuery.java:68)
	at jodd.db.oom.DbOomQuery.find(DbOomQuery.java:474)
	at jodd.db.oom.DbOomQuery.find(DbOomQuery.java:467)
	at jodd.db.oom.dao.GenericDao.findById(GenericDao.java:179)
	at io.github.joy.core.dao.JoyDao.findById(JoyDao.java:51)
	at io.github.joy.hotel.service.LoginService.setLoginMemberInfo(LoginService.java:32)
	at io.github.joy.hotel.service.LoginService$$JoddProxy.setLoginMemberInfo$0(Unknown Source)
	at io.github.joy.hotel.service.LoginService$$JoddProxy.setLoginMemberInfo(Unknown Source)
	at io.github.joy.hotel.interceptor.ApiInterceptor.intercept(ApiInterceptor.java:40)
	at jodd.madvoc.interceptor.ActionInterceptor.apply(ActionInterceptor.java:38)
	at jodd.madvoc.ActionRequest.invoke(ActionRequest.java:240)
	at jodd.joy.i18n.I18nInterceptor.intercept(I18nInterceptor.java:46)
	at jodd.madvoc.interceptor.ActionInterceptor.apply(ActionInterceptor.java:38)
	at jodd.madvoc.ActionRequest.invoke(ActionRequest.java:240)
	at jodd.madvoc.ActionRequest.lambda$createExecutionArray$0(ActionRequest.java:209)
	at jodd.madvoc.ActionRequest.invoke(ActionRequest.java:240)
	at jodd.madvoc.component.MadvocController.invoke(MadvocController.java:163)
	at jodd.madvoc.MadvocServletFilter.doFilter(MadvocServletFilter.java:109)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1634)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:533)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:146)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:257)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1595)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1253)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:473)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1564)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1155)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:219)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:126)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:531)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:352)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:260)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:281)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:102)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:319)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:175)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:139)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:754)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:672)
	at java.lang.Thread.run(Thread.java:748)

```
## Current behavior
The above code ,if open sql debug mode ,exception happened;
```
at jodd.db.oom.dao.GenericDao.findById(GenericDao.java:179)
```
If close the sql debug mode,the world is silent!

## Expected behavior

Sql debug mode should be as normal mode and execute normal success!

## Steps to Reproduce the Problem
sql generation ?

**Comment by igr** [comment]
Working on it - I will remove proxetta from this, and make a proper wrapper.

**Comment by igr** [comment]
Fixed :)
