### ISSUE TITLE
decora cannot decora static file on tomcat!

### ISSUE THREAD

**Issue by yujinping** [oblac/jodd#686]
Using static file: `/layouts/main.html` as the layout page.
Content page is like `/admin/test.html`

**DefaultDecoraManager.java**

```java
public class DefaultDecoraManager extends DecoraManager {
    private static final Logger logger = LoggerFactory.getLogger(DefaultDecoraManager.class);

    private static final String ADMIN_HTML="/layouts/main.html";
    @Override
    public String resolveDecorator(HttpServletRequest request, String actionPath) {
        logger.info("Request path={}",actionPath);
        if (Wildcard.match(actionPath, "/admin/*")) {
            return ADMIN_HTML;
        }
        return null;
    }
}
```

**/layouts/main.html**

```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title><span id="decora-title">default title</span></title>
    <span id="decora-head">default title</span>
</head>
<body>
<div id="wrapper">
    <div>text in the layout!</div>
    <div id="decora-body"></div>
</div>
</body>
</html>
```

**/admin/test.html**
```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>test</title>
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=0">
</head>
<body>
<div id="main">
    test here!
</div>
</body>
</html>

```
## Current behavior
```text
11:05:29.448 [http-nio-8080-exec-1] INFO  io.github.joy.hotel.DefaultDecoraManager - Request path=/admin/test.html
三月 08, 2019 11:05:29 上午 org.apache.catalina.core.StandardWrapperValve invoke
严重: Servlet.service() for servlet [default] in context with path [] threw exception
java.lang.NullPointerException
	at jodd.lagarto.Scanner.initialize(Scanner.java:48)
	at jodd.lagarto.LagartoParser.initialize(LagartoParser.java:90)
	at jodd.lagarto.LagartoParser.<init>(LagartoParser.java:75)
	at jodd.decora.parser.DecoraParser.parseDecorator(DecoraParser.java:57)
	at jodd.decora.parser.DecoraParser.decorate(DecoraParser.java:44)
	at jodd.decora.DecoraServletFilter.doFilter(DecoraServletFilter.java:176)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:212)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:94)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:492)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:141)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:80)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:502)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1152)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:684)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1539)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1495)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
```

## Expected behavior

decora the page success and render the result page correct!

## Steps to Reproduce the Problem

if I proxy the static html files behind an Servlet like this:
```java
public class HtmlServlet extends HttpServlet {
    private static final Logger logger = LoggerFactory.getLogger(HtmlServlet.class);

    @Override
    public void init(ServletConfig config) throws ServletException {
        super.init(config);
    }
    private String findFile(String file){
        String page = file;
        if(file.endsWith(".html")==false && file.endsWith("/")==false)
            page = page+"/";
            if(page.endsWith("/")==true)
                page=page+"index.html";
        return page;
    }
    @Override
    protected void service(HttpServletRequest req, HttpServletResponse resp) throws ServletException, IOException {
        req.getRequestURI();
        String file = req.getServletContext().getRealPath(req.getRequestURI());
        logger.info("file={}",file);
        String page = findFile(file);
        logger.info("page={}",page);
        resp.setCharacterEncoding("utf-8");
        Writer writer = resp.getWriter();
        try {
            String content = FileUtil.readUTFString(page);
            writer.write(content);
        }catch (IOException ex){
            resp.setStatus(HttpServletResponse.SC_NOT_FOUND);
        }
        writer.flush();
        writer.close();
    }
}
```
and web.xml configuration:
```xml
    <filter>
        <filter-name>decora</filter-name>
        <filter-class>jodd.decora.DecoraServletFilter</filter-class>
        <init-param>
            <param-name>decora.manager</param-name>
            <param-value>io.github.joy.hotel.DefaultDecoraManager</param-value>
        </init-param>
    </filter>
    <filter-mapping>
        <filter-name>decora</filter-name>
        <url-pattern>/admin/*</url-pattern>
    </filter-mapping>
    <servlet>
        <servlet-name>html</servlet-name>
        <servlet-class>io.github.joy.hotel.servlet.HtmlServlet</servlet-class>
    </servlet>
    <servlet-mapping>
        <servlet-name>html</servlet-name>
        <url-pattern>*.html</url-pattern>
    </servlet-mapping>
```

the decora result is successful. Remove the servlet mapping, exception happened as above!
I wanna pure static html file to be decora success,not using servlet mapping!

**Comment by igr** [comment]
See release notes :)

**Comment by yujinping** [comment]
Not resolve the problem! @igr Could you  show a example code for me ?

**Comment by igr** [comment]
The idea is to use `DefaultDecoraManager` and somewhere on the init (in ctor or later) you can register the content or files that you want to be served for decora templates.

You can say: `registerDecoraContent(ADMIN_HTML, new File(....)` and later, when `ADMIN_HTML` is recognized as a template, it will be read or returned from memory.

In other words, you can map decora template names with some content (file or `char[]`).
