### ISSUE TITLE
no execution of benchmarks possible

### ISSUE THREAD

**Issue by moh-sushi** [oblac/jodd#738]
Hi,

i have problems with execution of the included benchmarks.

at root directory i use following command:

`gradlew  :jodd-core:Base32Benchmark  -Dfile.encoding=UTF-8 -Duser.country=US -Duser.language=us  --stacktrace`

Following stacktrace / error will be reported :

```
> Configure project :
-----------------
 Jodd 5.1.0-20191101

 snapshot: true
 java: v1.8
 date: 20191101
-----------------

Running Benchmark: Base32Benchmark


> Task :jodd-core:Base32Benchmark FAILED
Exception in thread "main" java.lang.RuntimeException: ERROR: Unable to find the resource: /META-INF/BenchmarkList
        at org.openjdk.jmh.runner.AbstractResourceReader.getReaders(AbstractResourceReader.java:98)
        at org.openjdk.jmh.runner.BenchmarkList.find(BenchmarkList.java:122)
        at org.openjdk.jmh.runner.Runner.internalRun(Runner.java:263)
        at org.openjdk.jmh.runner.Runner.run(Runner.java:209)
        at org.openjdk.jmh.Main.main(Main.java:71)

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':jodd-core:Base32Benchmark'.
> Process 'command 'C:\Program Files\AdoptOpenJDK\jdk-8.0.232.09-hotspot\bin\java.exe'' finished with non-zero exit value 1

* Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':jodd-core:Base32Benchmark'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$3.accept(ExecuteActionsTaskExecuter.java:151)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$3.accept(ExecuteActionsTaskExecuter.java:148)
        at org.gradle.internal.Try$Failure.ifSuccessfulOrElse(Try.java:191)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:141)
		...........
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
Caused by: org.gradle.process.internal.ExecException: Process 'command 'C:\Program Files\AdoptOpenJDK\jdk-8.0.232.09-hotspot\bin\java.exe'' finished with non-zero exit value 1
        at org.gradle.process.internal.DefaultExecHandle$ExecResultImpl.assertNormalExitValue(DefaultExecHandle.java:396)
		...........
        at org.gradle.internal.execution.steps.ResolveCachingStateStep.execute(ResolveCachingStateStep.java:90)
        at org.gradle.internal.execution.steps.ResolveCachingStateStep.execute(ResolveCachingStateStep.java:48)
        at org.gradle.internal.execution.impl.DefaultWorkExecutor.execute(DefaultWorkExecutor.java:33)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:120)
        ... 126 more


* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/5.4.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 2s
22 actionable tasks: 1 executed, 21 up-to-date
```

Is this a local issue?
Or does anyone have this issue , too?
Can anyone maybe help me?

Thanks!

Greetz

**Comment by igr** [comment]
This is gradle change, need to mark JMH as annotation processor.
